local aerial = require("aerial")

aerial.setup({
  backends = { "lsp" },
  min_width = 35,
  max_width = 35,
  highlight_on_jump = 0,
  close_on_select = true,
  show_guides = true,
  filter_kind = {
    'Array',
    'Boolean',
    'Class',
    -- 'Constantd',
    'Constructor',
    'Enum',
    'EnumMember',
    -- 'Event',
    -- 'Field',
    -- 'File',
    'Function',
    -- 'Interface',
    -- 'Key',
    -- 'Method',
    'Module',
    -- 'Null',
    'Object',
    -- 'Package',
    -- 'Property',
    'String',
    'Struct',
    -- 'TypeParameter',
    'Variable',
    -- "Class",
    -- "Constructor",
    -- "Enum",
    -- "Function",
    -- "Interface",
    -- "Module",
    -- "Method",
    -- "Struct",
  },
  icons = {
    File          = "",
    Module        = "",
    Namespace     = ":",
    Package       = "",
    Class         = "ﴯ",
    Method        = "",
    Property      = "ﰠ",
    Field         = "ﰠ",
    Constructor   = "⌘",
    Enum          = "",
    Interface     = "",
    Function      = "",
    Variable      = "",
    Constant      = "",
    String        = "",
    Number        = "#",
    Boolean       = "",
    Array         = "",
    Object        = "",
    Key           = "",
    Null          = "␀",
    EnumMember    = "",
    Struct        = "ﳤ",
    Event         = "",
    Operator      = "",
    TypeParameter = "",
  },
})
