pcall(require, "impatient")
require("core.globals")
require("core.plug.core")
require("core.winbar")
require("core.config")
require("core.plug.lsp.init")
require("core.maps")
require("core.packer")
require("packerC.packerComp")
