pcall(require, "impatient")
require("core.globals")
require("core.bfs")
require("core.plug.neoScroll")
require("core.config")
require("core.plug.transp")
require("core.plug.fidget")
require("core.plug.lsp.init")
require("core.maps")
require("core.packer")
require("core.packerC.packerComp")
require("core.winbar")
