pcall(require, "impatient")
require("core.plugins.neoScroll")
require("core.utils")
require("core.packer")
require("core.plugins.lsp.init")
require("core.globals")
require("core.winbar")
require("core.plugins.fidget")
require("core.plugins.transp")
