require("user.autopairs")
require("user.luasnip")
require("user.cmp")
require("user.gitsigns")
require("user.impatient")
require("user.lualine")
require("user.neoterm")
require("user.nvim-tree")
require("user.telescope")
require("user.treesitter")
require("user.trouble")
require("user.ts-autotag")
require("user.ts-rainbow")
require("user.discord-presence")
require("user.impatient")

